- name: Настройка серверов
  hosts: web_servers
  become: yes
  tasks:
    - name: Выполнить обновление
      yum:
        name: '*'
        state: latest

    - name: Установка EPEL
      yum:
        name: epel-release
        state: present

    - name: Установка необходимых пакетов
      yum:
        name:
          - nano
          - nginx
          - php
          - php-fpm
          - git
        state: present

    - name: Включить службу Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Установка firewalld
      yum:
        name: firewalld
        state: present

    - name: Запуск firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Открыть порт 80 в firewall
      shell: "firewall-cmd --add-port=80/tcp --permanent"

    - name: Открыть порт 443 в firewall
      shell: "firewall-cmd --add-port=443/tcp --permanent"

    - name: Замена настроек PHP-FPM
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: 'user = apache'
        replace: 'user = nginx'

    - name: Замена настроек PHP-FPM
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: 'group = apache'
        replace: 'group = nginx'

    - name: Замена настроек PHP-FPM
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: ';listen.owner = nobody'
        replace: ';listen.owner = nginx'

    - name: Замена настроек PHP-FPM
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: ';listen.group = nobody'
        replace: ';listen.group = nginx'

    - name: Замена настроек PHP-FPM
      replace:
        path: /etc/php-fpm.d/www.conf
        regexp: ';listen.mode\s*='
        replace: 'listen.mode = 0660'

    - name: Перезапуск службы PHP-FPM
      systemd:
        name: php-fpm
        state: restarted

  handlers:
    - name: Перезагрузка Nginx
      service:
        name: nginx
        state: restarted
